services:
  airflow-webserver:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS: /keys/${GCP_KEY_FILENAME}
      - BQ_PROJECT_ID: ${BQ_PROJECT_ID}
      - BQ_DATASET_RAW: ${BQ_DATASET_RAW}
      - BQ_TABLE_RAW: ${BQ_TABLE_RAW}
      - BQ_LOCATION: ${BQ_LOCATION}
    volumes:
      - ./:/project
      - ${HOST_KEYS_DIR}:/keys:ro
      - ${HOST_DBT_DIR:-~/.dbt}:/home/airflow/.dbt:ro

  airflow-scheduler:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS: /keys/${GCP_KEY_FILENAME}
      - BQ_PROJECT_ID: ${BQ_PROJECT_ID}
      - BQ_DATASET_RAW: ${BQ_DATASET_RAW}
      - BQ_TABLE_RAW: ${BQ_TABLE_RAW}
      - BQ_LOCATION: ${BQ_LOCATION}
    volumes:
      - ./:/project
      - ${HOST_KEYS_DIR}:/keys:ro
      - ${HOST_DBT_DIR:-~/.dbt}:/home/airflow/.dbt:ro

  airflow-worker:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS: /keys/${GCP_KEY_FILENAME}
      - BQ_PROJECT_ID: ${BQ_PROJECT_ID}
      - BQ_DATASET_RAW: ${BQ_DATASET_RAW}
      - BQ_TABLE_RAW: ${BQ_TABLE_RAW}
      - BQ_LOCATION: ${BQ_LOCATION}
    volumes:
      - ./:/project
      - ${HOST_KEYS_DIR}:/keys:ro
      - ${HOST_DBT_DIR:-~/.dbt}:/home/airflow/.dbt:ro

  airflow-init:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS: /keys/${GCP_KEY_FILENAME}
      - BQ_PROJECT_ID: ${BQ_PROJECT_ID}
      - BQ_DATASET_RAW: ${BQ_DATASET_RAW}
      - BQ_TABLE_RAW: ${BQ_TABLE_RAW}
      - BQ_LOCATION: ${BQ_LOCATION}
      - AIRFLOW_UID: ${AIRFLOW_UID}
    volumes:
      - ./:/project
      - ${HOST_KEYS_DIR}:/keys:ro
      - ${HOST_DBT_DIR:-~/.dbt}:/home/airflow/.dbt:ro