name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (scraper + tooling)
        run: |
          python -m pip install --upgrade pip
          pip install -r services/scraper/requirements.txt
          pip install black ruff isort pytest dbt-bigquery sqlfluff sqlfluff-templater-dbt

      - name: Pre-commit (quick)
        run: |
          pip install pre-commit
          pre-commit run --all-files || true

      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'EOF'
          default:
            outputs:
              dev:
                type: bigquery
                method: service-account-json
                project: ${{ secrets.BQ_PROJECT_ID }}
                dataset: fx_dev
                keyfile_json: ${{ secrets.GCP_SA_KEY_JSON }}
                location: US
                threads: 4
            target: dev
          EOF

      - name: dbt deps/compile/test
        run: |
          cd dbt
          dbt deps
          dbt compile --profiles-dir ~/.dbt               # creates target/manifest.json
          dbt build --profiles-dir ~/.dbt \
            --select state:modified+ \
            --state target \
            --defer


      - name: Run unit tests
        run: pytest -q